import requests
from requests.auth import HTTPBasicAuth

print("GET on 8080/test")
r = requests.get('http://localhost:8080/test')
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")

print("GET on 8080/test/index.html with no language parameter")
r = requests.get('http://localhost:8080/test/index.html')
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")

print("GET on 8080/test/index.html with preferred language FR")
headers = {'Accept-Language': 'fr'}
r = requests.get('http://localhost:8080/test/index.html', headers=headers)
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")

print("GET on 8080/test/index.html with preferred language EN")
headers = {'Accept-Language': 'en'}
r = requests.get('http://localhost:8080/test/index.html', headers=headers)
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")

print("GET on 8080/auth/add.html without auth")
r = requests.get('http://localhost:8080/auth/add.html')
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")

print("GET on 8080/auth/add.html with auth")
r = requests.get('http://localhost:8080/auth/add.html', auth=HTTPBasicAuth('test', 'test'))
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")

print("GET on 8080/auth/ with auth")
r = requests.get('http://localhost:8080/auth/', auth=HTTPBasicAuth('test', 'test'))
print("==STATUSCODE==")
print(r.status_code)
print("==HEADERS==")
print(r.headers)
print("==BODY==")
print(r.text)
print("========")